services:
  microns-opc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_HOST_PORT:-8888}:8888"
    volumes:
      - ./:/workdir
      - /mnt:/mnt
    working_dir: /workdir
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
    entrypoint:
      - sh
      - -lc
      - >
        /opt/venv/bin/python -m pip install -e /workdir &&
        exec /opt/venv/bin/python -m jupyterlab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --allow-root
        --ServerApp.token=$$JUPYTER_TOKEN
        --IdentityProvider.token=$$JUPYTER_TOKEN

  uv-lock:
    image: ubuntu:24.04
    working_dir: /workdir
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - UV_NO_COLOR=1
      - TZ=UTC
    volumes:
      - ../:/workdir
    entrypoint: >
      bash -lc "set -Eeuo pipefail
      && apt-get update
      && apt-get install -y --no-install-recommends python3 python3-venv curl ca-certificates git
      && curl -LsSf https://astral.sh/uv/install.sh | sh
      && /root/.local/bin/uv --version
      && /root/.local/bin/uv lock"
    tty: false
    stdin_open: false